//
// Created by toose on 10/23/2024.
//

#ifndef MACHINELANGUAGE_SIMULATOR_INSTRUCTIONREGISTER_H
#define MACHINELANGUAGE_SIMULATOR_INSTRUCTIONREGISTER_H


class InstructionRegister {

};


#endif //MACHINELANGUAGE_SIMULATOR_INSTRUCTIONREGISTER_H
