//
// Created by toose on 10/23/2024.
//

#ifndef MACHINELANGUAGE_SIMULATOR_PROGRAMCOUNTER_H
#define MACHINELANGUAGE_SIMULATOR_PROGRAMCOUNTER_H


class ProgramCounter {

};


#endif //MACHINELANGUAGE_SIMULATOR_PROGRAMCOUNTER_H
